language: node_js
sudo: required
dist: xenial
before_script:
  - npm install web-component-tester
  - npm install bower
  - 'export PATH=$PWD/node_modules/.bin:$PATH'
  - bower install
node_js: 8
addons:
  firefox: latest
  chrome: stable
script:
  - xvfb-run wct --skip-plugin sauce
  - "if [ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ]; then wct --skip-plugin local --plugin sauce; fi"
